name: product_class
label: 产品类别
icon: product_class
enable_search: true
enable_api: true
fields:
    name:
        type: text
        label: 类别名称
        defaultValue: ''
        searchable: true
        required: true
        sortable: true
    remark:
        type: text
        label: 备注
list_views:
    all:
        label: 全部
        columns:
            - name
            - remark
permission_set:
    user:
        allowCreate: true
        allowDelete: true
        allowEdit: true
        allowRead: true
        modifyAllRecords: true
        viewAllRecords: true